name: taskflow
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mysql1: ^0.20.0
  get: ^4.6.6
  http: ^1.1.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.2.2
  crypto: ^3.0.3
  flutter_feather_icons: ^2.0.0+1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  mailer: ^6.0.1
  dio: ^5.5.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
